-- Speed Limiter --
if Config.speedlimiter then
Citizen.CreateThread(function()
	while true do 
		Citizen.Wait(10)
		local ped = PlayerPedId()
		local vehicle = GetVehiclePedIsIn(ped, false)
		local speed = GetEntitySpeed(vehicle)
        local class = GetVehicleClass(vehicle)
			if (ped) then
                if class == 16 then
                    -- planes
                else
                if class == 15 then
                    -- helicopters
                else
                if class == 18 then
                    if math.floor(speed*2.2369) == Config.emergencyclassSpeedlimit then
                        cruise = speed
                        SetEntityMaxSpeed(vehicle, cruise)
                    end
                else
				if math.floor(speed*2.2369) == Config.speedlimit then
					cruise = speed
					SetEntityMaxSpeed(vehicle, cruise)
					end
				end
			end
		end
    end
end
end)
end

-- Anti VDM --
if Config.antivdm then
Citizen.CreateThread(function()
    while true do
        SetWeaponDamageModifier(-1553120962, 0.0)
        Wait(0)
    end
end)
end

-- Disable Vehicle Weapons --
if Config.disablevehicleweapons then
local vehicle_weapons = {
	"VEHICLE_WEAPON_WATER_CANNON",
	"VEHICLE_WEAPON_PLAYER_LAZER",
	"VEHICLE_WEAPON_PLANE_ROCKET",
	"VEHICLE_WEAPON_ENEMY_LASER",
	"VEHICLE_WEAPON_TANK",
	"VEHICLE_WEAPON_SEARCHLIGHT",
	"VEHICLE_WEAPON_RADAR",
	"VEHICLE_WEAPON_PLAYER_BUZZARD",
	"VEHICLE_WEAPON_SPACE_ROCKET",
	"VEHICLE_WEAPON_TURRET_INSURGENT",
	"VEHICLE_WEAPON_PLAYER_SAVAGE",
	"VEHICLE_WEAPON_TURRET_TECHNICAL",
	"VEHICLE_WEAPON_NOSE_TURRET_VALKYRIE",
	"VEHICLE_WEAPON_TURRET_VALKYRIE",
	"VEHICLE_WEAPON_CANNON_BLAZER",
	"VEHICLE_WEAPON_TURRET_BOXVILLE",
	"VEHICLE_WEAPON_RUINER_BULLET",
	"VEHICLE_WEAPON_RUINER_ROCKET",
	"VEHICLE_WEAPON_HUNTER_MG",
	"VEHICLE_WEAPON_HUNTER_MISSILE",
	"VEHICLE_WEAPON_HUNTER_CANNON",
	"VEHICLE_WEAPON_HUNTER_BARRAGE",
	"VEHICLE_WEAPON_TULA_NOSEMG",
	"VEHICLE_WEAPON_TULA_MG",
	"VEHICLE_WEAPON_TULA_DUALMG",
	"VEHICLE_WEAPON_TULA_MINIGUN",
	"VEHICLE_WEAPON_SEABREEZE_MG",
	"VEHICLE_WEAPON_MICROLIGHT_MG",
	"VEHICLE_WEAPON_DOGFIGHTER_MG",
	"VEHICLE_WEAPON_DOGFIGHTER_MISSILE",
	"VEHICLE_WEAPON_MOGUL_NOSE",
	"VEHICLE_WEAPON_MOGUL_DUALNOSE",
	"VEHICLE_WEAPON_MOGUL_TURRET",
	"VEHICLE_WEAPON_MOGUL_DUALTURRET",
	"VEHICLE_WEAPON_ROGUE_MG",
	"VEHICLE_WEAPON_ROGUE_CANNON",
	"VEHICLE_WEAPON_ROGUE_MISSILE",
	"VEHICLE_WEAPON_BOMBUSHKA_DUALMG",
	"VEHICLE_WEAPON_BOMBUSHKA_CANNON",
	"VEHICLE_WEAPON_HAVOK_MINIGUN",
	"VEHICLE_WEAPON_VIGILANTE_MG",
	"VEHICLE_WEAPON_VIGILANTE_MISSILE",
	"VEHICLE_WEAPON_TURRET_LIMO",
	"VEHICLE_WEAPON_DUNE_MG",
	"VEHICLE_WEAPON_DUNE_GRENADELAUNCHER",
	"VEHICLE_WEAPON_DUNE_MINIGUN",
	"VEHICLE_WEAPON_TAMPA_MISSILE",
	"VEHICLE_WEAPON_TAMPA_MORTAR",
	"VEHICLE_WEAPON_TAMPA_FIXEDMINIGUN",
	"VEHICLE_WEAPON_TAMPA_DUALMINIGUN",
	"VEHICLE_WEAPON_HALFTRACK_DUALMG",
	"VEHICLE_WEAPON_HALFTRACK_QUADMG",
	"VEHICLE_WEAPON_APC_CANNON",
	"VEHICLE_WEAPON_APC_MISSILE",
	"VEHICLE_WEAPON_APC_MG",
	"VEHICLE_WEAPON_ARDENT_MG",
	"VEHICLE_WEAPON_TECHNICAL_MINIGUN",
	"VEHICLE_WEAPON_INSURGENT_MINIGUN",
	"VEHICLE_WEAPON_TRAILER_QUADMG",
	"VEHICLE_WEAPON_TRAILER_MISSILE",
	"VEHICLE_WEAPON_TRAILER_DUALAA",
	"VEHICLE_WEAPON_NIGHTSHARK_MG",
	"VEHICLE_WEAPON_OPPRESSOR_MG",
	"VEHICLE_WEAPON_OPPRESSOR_MISSILE",
	"VEHICLE_WEAPON_MOBILEOPS_CANNON",
	"VEHICLE_WEAPON_AKULA_TURRET_SINGLE",
	"VEHICLE_WEAPON_AKULA_MISSILE",
	"VEHICLE_WEAPON_AKULA_TURRET_DUAL",
	"VEHICLE_WEAPON_AKULA_MINIGUN",
	"VEHICLE_WEAPON_AKULA_BARRAGE",
	"VEHICLE_WEAPON_AVENGER_CANNON",
	"VEHICLE_WEAPON_BARRAGE_TOP_MG",
	"VEHICLE_WEAPON_BARRAGE_TOP_MINIGUN",
	"VEHICLE_WEAPON_BARRAGE_REAR_MG",
	"VEHICLE_WEAPON_BARRAGE_REAR_MINIGUN",
	"VEHICLE_WEAPON_BARRAGE_REAR_GL",
	"VEHICLE_WEAPON_CHERNO_MISSILE",
	"VEHICLE_WEAPON_COMET_MG",
	"VEHICLE_WEAPON_DELUXO_MG",
	"VEHICLE_WEAPON_DELUXO_MISSILE",
	"VEHICLE_WEAPON_KHANJALI_CANNON",
	"VEHICLE_WEAPON_KHANJALI_CANNON_HEAVY",
	"VEHICLE_WEAPON_KHANJALI_MG",
	"VEHICLE_WEAPON_KHANJALI_GL",
	"VEHICLE_WEAPON_REVOLTER_MG",
	"VEHICLE_WEAPON_WATER_CANNON",
	"VEHICLE_WEAPON_SAVESTRA_MG",
	"VEHICLE_WEAPON_SUBCAR_MG",
	"VEHICLE_WEAPON_SUBCAR_MISSILE",
	"VEHICLE_WEAPON_SUBCAR_TORPEDO",
	"VEHICLE_WEAPON_THRUSTER_MG",
	"VEHICLE_WEAPON_THRUSTER_MISSILE",
	"VEHICLE_WEAPON_VISERIS_MG",
	"VEHICLE_WEAPON_VOLATOL_DUALMG"
}

Citizen.CreateThread(function()
    while true do
        Citizen.Wait(10)
		local player2 = PlayerPedId()
		local vehicle2 = GetVehiclePedIsIn(player2, false)
		if DoesVehicleHaveWeapons(vehicle2) then
			for _,v in next, vehicle_weapons do
				DisableVehicleWeapon(true, GetHashKey(v), vehicle2, player2)	
			end
		end
    end
end)
end